application:
  subdomain: glash
  entries:
    - id: main
      title: "Dashboard"
      path: /ui/
  upstreams:
    - location: /
      backend: http://host.lzcapp:9090/
  public_path:
    - /

services:
  glash:
    image: docker.1ms.run/gangz1o/glash:2.1.6
    healthcheck:
      disable: true
    network_mode: host
    environment:
      - TZ={{.U.tz}}
      - SUB_URL={{.U.sub_url}}
      - SUB_CRON={{.U.sub_cron}}
      - SECRET={{.U.secret}}
      - ALLOW_LAN={{.U.allow_lan}}
    binds:
      - /lzcapp/var/config:/root/.config/mihomo
